name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write # required for requesting the JWT
  contents: read # required for checkout
  pull-requests: write # required for posting comments to pull requests

env:
  AWS_REGION: us-east-1
  TF_BACKEND_BUCKET_REGION: us-east-2
  TF_BACKEND_BUCKET: tf-bucket

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy Winglang App
        uses: winglang/wing-github-action/actions/deploy@main
        with:
          entry: "main.w" # Required, replace this with your entry file if different
          target: "tf-aws" # Required, the target to deploy to. e.g. tf-aws, tf-gcp, tf-azure or awscdk.
          version: "latest" # Optional, specify a different version of the Winglang CLI if required
          working-directory: "" # Optional, the working directory to use. e.g. ./examples/with-dependencies. Will set backend-scope to the relative path of the working directory.
          backend: "s3" # Optional, currently only 's3' is supported
        env:
          TF_BACKEND_BUCKET: ${{ env.TF_BACKEND_BUCKET }} # required, only required if s3 backend is
          TF_BACKEND_BUCKET_REGION: ${{ env.TF_BACKEND_BUCKET_REGION }} #  required, only required if s3 backend is
