name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: us-east-1
  TF_BACKEND_BUCKET_REGION: us-east-1

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Get list of directories and save them to the output
        id: setdirs
        shell: bash
        run: |
          dirs=$(ls -d $PWD/* | sed 's/\/$//' | grep -v "README.md\|.gitignore\|usage-notification" | jq -R -s -c 'split("\n")[:-1]')
          processed_dirs=$(echo "{ \"directory\": $dirs }" | jq -c '[ .directory[] | {directory: ., name: (split("/") | last)}]')
          wrapped_dirs=$(echo $processed_dirs | jq -c .)
          echo "dirs=$wrapped_dirs" >> $GITHUB_OUTPUT
    outputs:
      projects: ${{ steps.setdirs.outputs.dirs }}

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projects: ${{ fromJson(needs.setup.outputs.projects) }}
    name: ${{ matrix.projects.name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy Winglang App
        uses: winglang/wing-github-action/actions/deploy@main
        with:
          entry: "main.w"
          target: "tf-aws"
          version: "latest"
          working-directory: ./${{matrix.projects.name}}
          backend: "s3"
        env:
          TF_BACKEND_BUCKET: wingbots-${{ matrix.projects.name }}
          TF_BACKEND_BUCKET_REGION: ${{ env.TF_BACKEND_BUCKET_REGION }}
