on: [pull_request]

permissions:
  id-token: write # required for requesting the JWT
  contents: read # required for checkout
  pull-requests: write # required for posting comments to pull requests

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
  TF_BACKEND_BUCKET_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: gh-actions-winglang
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy Winglang App
        uses: winglang/wing-github-action/actions/deploy@main
        with:
          entry: "main.wing" # Required, replace this with your entry file if different
          target: "tf-aws" # Required, the target to deploy to. e.g. tf-aws, tf-gcp, tf-azure or awscdk.
          version: "latest" # Optional, specify a different version of the Winglang CLI if required
          working-directory: "" # Optional, the working directory to use. e.g. ./examples/with-dependencies. Will set backend-scope to the relative path of the working directory.
          backend: "s3" # Optional, currently only 's3' is supported
        env:
          TF_BACKEND_BUCKET: "<your-bucket-name>" # required, only required if s3 backend is
          TF_BACKEND_BUCKET_REGION: "<your-bucket-region>" #  required, only required if s3 backend is
