name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  AWS_REGION: us-east-1
  NODE_VERSION: "18.16.0"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Get list of directories and save them to the output
        id: setdirs
        shell: bash
        run: |
          dirs=$(ls -d | sed 's/\/$//' | grep -v "README.md\|.gitignore" | jq -R -s -c 'split("\n")[:-1]')
          processed_dirs=$(echo "{ \"directory\": $dirs }" | jq -c '[ .directory[] | {directory: ., name: (split("/") | last)}]')
          wrapped_dirs=$(echo $processed_dirs | jq -c .)
          echo "dirs=$wrapped_dirs" >> $GITHUB_OUTPUT
    outputs:
      projects: ${{ steps.setdirs.outputs.dirs }}

  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projects: ${{ fromJson(needs.setup.outputs.projects) }}
        target: ["sim", "tf-aws"]
    name: ${{ matrix.projects.name }} - ${{ matrix.target }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        if: matrix.target == 'tf-aws'
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Wing
        run: |
          npm install -g winglang
          wing --version

      - name: Test
        run: |
          cd ${{ matrix.projects.directory }}
          wing test -t ${{matrix.target}} **/*.test.w
